services:  
  backend:
    build:
      context: ./back
    ports:
      - 8001:8080
    environment:
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL}
      - CORS_ORIGIN=${CORS_ORIGIN}
    networks:
      http:
    # labels:
    #   - "traefik.enable=true"
    #   - "traefik.http.routers.backend.rule=Host(`${HOSTNAME}`) && PathPrefix(`/api`)"
    #   - "traefik.http.services.backend.loadbalancer.server.port=8080"
    #   - "traefik.http.routers.backend.entrypoints=http"
  frontend:
    build:
      context: ./front
    environment:
      - NEXT_PUBLIC_API_BASE=${NEXT_PUBLIC_API_BASE}
    ports:
      - 8000:3000
    networks:
      http:
    # labels:
    #   - "traefik.enable=true"
    #   - "traefik.http.routers.frontend.rule=Host(`${HOSTNAME}`) && PathPrefix(`/`)"
    #   - "traefik.http.services.frontend.loadbalancer.server.port=5173"
    #   - "traefik.http.routers.frontend.entrypoints=http"

networks:
  http:
   external: true
  backdb:
    external: true