services:  
  backend:
    build:
      context: ./back
    ports:
      - 8001:8080
    environment:
      - OLLAMA_BASE_URL='http://10.15.0.20:11434'
    networks:
      http:
    # labels:
    #   - "traefik.enable=true"
    #   - "traefik.http.routers.backend.rule=Host(`${HOSTNAME}`) && PathPrefix(`/api`)"
    #   - "traefik.http.services.backend.loadbalancer.server.port=8080"
    #   - "traefik.http.routers.backend.entrypoints=http"
  frontend:
    build:
      context: ./front
    ports:
      - 8000:5173
    networks:
      http:
    # labels:
    #   - "traefik.enable=true"
    #   - "traefik.http.routers.frontend.rule=Host(`${HOSTNAME}`) && PathPrefix(`/`)"
    #   - "traefik.http.services.frontend.loadbalancer.server.port=5173"
    #   - "traefik.http.routers.frontend.entrypoints=http"

networks:
  http:
   external: true
  backdb:
    external: true