services:
  traefik:
    image: traefik:v3.3.4
    pull_policy: always
    container_name: traefik
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedByDefault=false"
      - "--entrypoints.web.address=:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/:/etc/traefik/:ro
      - $VOLUME_TRAEFIK/letsencrypt:/letsencrypt:rw
    networks:
      http:
      backdb:
    restart: unless-stopped

networks:
  http:
  backdb: