services:  
  backend:
    build:
      context: ./back
    networks:
      http:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`${HOSTNAME}`) && PathPrefix(`/api`)"
      - "traefik.http.services.backend.loadbalancer.server.port=8080"
      - "traefik.http.routers.backend.entrypoints=http"
  frontend:
    build:
      context: ./front
    networks:
      http:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`${HOSTNAME}`) && PathPrefix(`/`)"
      - "traefik.http.services.frontend.loadbalancer.server.port=5173"
      - "traefik.http.routers.frontend.entrypoints=http"

networks:
  http:
   external: true
  backdb:
    external: true