services:
  frontend:
    build:
      context: .
    networks:
      http:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=PathPrefix(`/`)"
      - "traefik.http.services.frontend.loadbalancer.server.port=5173"
networks:
  http:
    external: true